# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            The Compendium
tagline:          'The Compendium'
description:      'A collection of notes and quick reference sheets.'
url:              https://github.com/rhombusbombus
baseurl:          https://rhombusbombus.github.io/Compendium/

author:
  name:           'rhombusbombus'
  url:            linktr.ee/kaileos

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/rhombusbombus/Compendium
